import = [ "~/.config/alacritty/themes/themes/rose-pine.toml" ]

[font]
size = 11.0

[env]
TERM = "xterm-256color"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

